package eu.dedalus.prescriptionmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BaseDrug implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("codice minsan")
	protected java.lang.String minsan;
	@org.kie.api.definition.type.Label("codice atc del farmaco")
	protected java.lang.String atc;
	@org.kie.api.definition.type.Label("Descrizione del farmaco")
	protected java.lang.String description;

	@org.kie.api.definition.type.Label("codice principio attivo")
	protected java.lang.Integer activeIngredient;

	public BaseDrug() {
	}

	public java.lang.String getMinsan() {
		return this.minsan;
	}

	public void setMinsan(java.lang.String minsan) {
		this.minsan = minsan;
	}

	public java.lang.String getAtc() {
		return this.atc;
	}

	public void setAtc(java.lang.String atc) {
		this.atc = atc;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Integer getActiveIngredient() {
		return this.activeIngredient;
	}

	public void setActiveIngredient(java.lang.Integer activeIngredient) {
		this.activeIngredient = activeIngredient;
	}

	public BaseDrug(java.lang.String minsan, java.lang.String atc,
			java.lang.String description, java.lang.Integer activeIngredient) {
		this.minsan = minsan;
		this.atc = atc;
		this.description = description;
		this.activeIngredient = activeIngredient;
	}

}