package eu.dedalus.prescriptionmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CarePlan implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    private java.lang.String id;
    private Integer activeIngredient;
	private String protocolNumber;

    public CarePlan() {
    }
    
    public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public String getProtocolNumber() {
		return this.protocolNumber;
	}

	public void setProtocolNumber(String protocolNumber) {
		this.protocolNumber = protocolNumber;
	}

	public java.lang.Integer getActiveIngredient() {
		return this.activeIngredient;
	}

	public void setActiveIngredient(java.lang.Integer activeIngredient) {
		this.activeIngredient = activeIngredient;
	}

	public CarePlan(java.lang.String id, java.lang.Integer activeIngredient,
			java.lang.String protocolNumber) {
		this.id = id;
		this.activeIngredient = activeIngredient;
		this.protocolNumber = protocolNumber;
	}


}