package eu.dedalus.prescriptionmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Diagnosis implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ICD9 code")
	private java.lang.String code;
	@org.kie.api.definition.type.Label("ICD9 description")
	private java.lang.String description;

	@org.kie.api.definition.type.Label(value = "guid for persistence")
	private java.lang.String id;

	public Diagnosis() {
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public Diagnosis(java.lang.String code, java.lang.String description,
			java.lang.String id) {
		this.code = code;
		this.description = description;
		this.id = id;
	}

}