package eu.dedalus.prescriptionmodel;

import eu.dedalus.prescriptionmodel.BaseDrug;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DrugIntolerance extends BaseDrug implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;

	public DrugIntolerance() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public DrugIntolerance(java.lang.String id,java.lang.String minsan, java.lang.String atc,
			java.lang.Integer activeIngredient, java.lang.String description) {
		this.id = id;
		this.minsan = minsan;
		this.atc = atc;
		this.activeIngredient = activeIngredient;
		this.description = description;
	}
}