package eu.dedalus.prescriptionmodel;
import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Exemption implements java.io.Serializable, Cloneable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	@org.kie.api.definition.type.Label("type on exemption (PAT, RED..)")
	private java.lang.String type;
	private java.lang.String code;
	private int weight = -1;

	private java.lang.String description;

	@org.kie.api.definition.type.Label("the problem which is associated the exemption")
	private java.lang.String problemCode;

	@org.kie.api.definition.type.Label("list of applicable drugs")
	private java.util.List<eu.dedalus.prescriptionmodel.ExemptionItem> drugs = new ArrayList<>();

	@org.kie.api.definition.type.Label("list of applicable procedures")
	private java.util.List<eu.dedalus.prescriptionmodel.ExemptionItem> procedures = new ArrayList<>();

	@org.kie.api.definition.type.Label(value = "global restriction of exemption")
	private java.lang.String restrictionText = null;

	public Exemption() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getProblemCode() {
		return this.problemCode;
	}

	public void setProblemCode(java.lang.String problemCode) {
		this.problemCode = problemCode;
	}

	public java.util.List<eu.dedalus.prescriptionmodel.ExemptionItem> getDrugs() {
		return this.drugs;
	}

	public void setDrugs(
			java.util.List<eu.dedalus.prescriptionmodel.ExemptionItem> drugs) {
		this.drugs = drugs;
	}

	public java.util.List<eu.dedalus.prescriptionmodel.ExemptionItem> getProcedures() {
		return this.procedures;
	}

	public void setProcedures(
			java.util.List<eu.dedalus.prescriptionmodel.ExemptionItem> procedures) {
		this.procedures = procedures;
	}

	@Override
	public Exemption clone() throws CloneNotSupportedException {
		return (Exemption) super.clone();
	}

	public java.lang.String getRestrictionText() {
		return this.restrictionText;
	}

	public void setRestrictionText(java.lang.String restrictionText) {
		this.restrictionText = restrictionText;
	}

	public Exemption(
			java.lang.String id,
			java.lang.String type,
			java.lang.String code,
			int weight,
			java.lang.String description,
			java.lang.String problemCode,
			java.util.List<eu.dedalus.prescriptionmodel.ExemptionItem> drugs,
			java.util.List<eu.dedalus.prescriptionmodel.ExemptionItem> procedures,
			java.lang.String restrictionText) {
		this.id = id;
		this.type = type;
		this.code = code;
		this.weight = weight;
		this.description = description;
		this.problemCode = problemCode;
		this.drugs = drugs;
		this.procedures = procedures;
		this.restrictionText = restrictionText;
	}
	
	public boolean isWithRestriction() {
		return !(restrictionText == null || restrictionText.isEmpty());
	}
	
	 @Override
	public String toString() {
		return "Exemption [type=" + type + ", code=" + code + ", weight=" + weight + ", description=" + description
				+ ", problemCode=" + problemCode + ", restrictionText=" + restrictionText + "]";
	}

}