package eu.dedalus.prescriptionmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Interaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Integer activeIngredient;
	private String effect;

	public Interaction() {
	}

	public String getEffect() {
		return this.effect;
	}

	public void setEffect(String effect) {
		this.effect = effect;
	}

	public java.lang.Integer getActiveIngredient() {
		return this.activeIngredient;
	}

	public void setActiveIngredient(java.lang.Integer activeIngredient) {
		this.activeIngredient = activeIngredient;
	}

	public Interaction(java.lang.Integer activeIngredient,
			java.lang.String effect) {
		this.activeIngredient = activeIngredient;
		this.effect = effect;
	}
}