package eu.dedalus.prescriptionmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcedureInteraction implements java.io.Serializable, Cloneable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("Codice Nomenclatore tariffario")
	private String code;	
	
	@org.kie.api.definition.type.Label("Descrizione")
	private java.lang.String description = null;


    public ProcedureInteraction() {
    }
    
    public ProcedureInteraction(java.lang.String code,  java.lang.String description) {
		this.code = code;
		this.description = description;
	}

    public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public java.lang.String getDescription() {
		return description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}


    @Override
	public ProcedureInteraction clone() throws CloneNotSupportedException {
		// Define a shallow copy for ProcedureInteraction element
		ProcedureInteraction d = (ProcedureInteraction) super.clone();
		return d;
	}
}