package eu.dedalus.prescriptionmodel;

import java.util.ArrayList;
import java.util.List;
import eu.dedalus.prescriptionmodel.Procedure;
import eu.dedalus.prescriptionmodel.Drug;
import eu.dedalus.prescriptionmodel.Admission;
import eu.dedalus.prescriptionmodel.PatientInfo;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class Validator implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Regione")
	@org.kie.api.definition.type.Description("physician region")
	private String region;
	@org.kie.api.definition.type.Label("Farmaci")
	private List<Drug> drugs = new ArrayList<>();

	@org.kie.api.definition.type.Label("physician asl")
	private String asl;

    @org.kie.api.definition.type.Label("MEF Credenziali presenti")
	private boolean haveCredentials = true;
	
	@org.kie.api.definition.type.Label("Accertamenti")
	private List<Procedure> procedures = new ArrayList<>();

	@org.kie.api.definition.type.Label("Informazioni del Paziente")
	private PatientInfo patientInfo;

	@org.kie.api.definition.type.Label(value = "Ricoveri")
	private List<Admission> admissions = new ArrayList<>();
	
	public boolean isHaveCredentials() {
		return haveCredentials;
	}

	public void setHaveCredentials(boolean haveCredentials) {
		this.haveCredentials = haveCredentials;
	}

	public PatientInfo getPatientInfo() {
		return patientInfo;
	}

	public void setPatientInfo(PatientInfo patientInfo) {
		this.patientInfo = patientInfo;
	}

	public Validator() {
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public List<Drug> getDrugs() {
		return this.drugs;
	}

	public void setDrugs(List<Drug> drugs) {
		this.drugs = drugs;
	}

	public String getAsl() {
		return this.asl;
	}

	public void setAsl(String asl) {
		this.asl = asl;
	}

	public java.util.List<Procedure> getProcedures() {
		return this.procedures;
	}

	public void setProcedures(List<Procedure> procedures) {
		this.procedures = procedures;
	}

	public List<Admission> getAdmissions() {
		return this.admissions;
	}

	public void setAdmissions(List<Admission> admissions) {
		this.admissions = admissions;
	}

	public Validator(String region,
			List<Drug> drugs,
			String asl,
			List<Procedure> procedures,
			PatientInfo patientInfo,
			List<Admission> admissions,
			boolean haveCredentials) {
		this.region = region;
		this.drugs = drugs;
		this.asl = asl;
		this.procedures = procedures;
		this.patientInfo = patientInfo;
		this.admissions = admissions;
		this.haveCredentials = haveCredentials;
	}
}